// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

public final class F {
  private F() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Podaci_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Podaci_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendNewComment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendNewComment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_komentari_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_komentari_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Topic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Topic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Comment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Comment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007f.proto\"\350\001\n\007Request\022\022\n\nrequest_id\030\001 \001(" +
      "\005\022\032\n\005topic\030\002 \001(\0132\006.TopicH\000\210\001\001\022\036\n\007comment" +
      "\030\003 \001(\0132\010.CommentH\001\210\001\001\022%\n\016commentParrent\030" +
      "\004 \001(\0132\010.CommentH\002\210\001\001\022\035\n\007op_type\030\005 \001(\0162\014." +
      "RequestType\022\023\n\006zamena\030\006 \001(\tH\003\210\001\001B\010\n\006_top" +
      "icB\n\n\010_commentB\021\n\017_commentParrentB\t\n\007_za" +
      "mena\"1\n\006Podaci\022\031\n\007comment\030\001 \001(\0132\010.Commen" +
      "t\022\014\n\004text\030\002 \001(\t\"B\n\016SendNewComment\022\031\n\007com" +
      "ment\030\001 \001(\0132\010.Comment\022\025\n\005topic\030\002 \001(\0132\006.To" +
      "pic\"M\n\tkomentari\022 \n\016parrentComment\030\001 \001(\013" +
      "2\010.Comment\022\036\n\014childComment\030\002 \001(\0132\010.Comme" +
      "nt\"5\n\005Topic\022\020\n\010topic_id\030\001 \001(\005\022\014\n\004text\030\002 " +
      "\001(\t\022\014\n\004user\030\003 \001(\t\"w\n\007Comment\022\022\n\ncomment_" +
      "id\030\001 \001(\005\022\027\n\017parentCommentId\030\002 \001(\005\022\014\n\004tex" +
      "t\030\003 \001(\t\022\020\n\010topic_id\030\004 \001(\005\022\014\n\004user\030\005 \001(\t\022" +
      "\021\n\ttimestamp\030\006 \001(\003\"`\n\010Response\022\036\n\006status" +
      "\030\001 \001(\0162\016.RequestStatus\022\022\n\nrequest_id\030\002 \001" +
      "(\005\022\024\n\007message\030\003 \001(\tH\000\210\001\001B\n\n\010_message\"6\n\010" +
      "LogEntry\022\024\n\014entryAtIndex\030\001 \001(\004\022\024\n\014logEnt" +
      "ryData\030\002 \001(\014\"o\n\013LogResponse\022\032\n\006status\030\001 " +
      "\001(\0162\n.LogStatus\022\024\n\014entryAtIndex\030\002 \001(\004\022\033\n" +
      "\016lastEntryIndex\030\003 \001(\004H\000\210\001\001B\021\n\017_lastEntry" +
      "Index\"\007\n\005Empty\"\017\n\rLeaderRequest\"4\n\nLeade" +
      "rInfo\022\020\n\010imLeader\030\001 \001(\010\022\024\n\014hostnamePort\030" +
      "\002 \001(\t*\214\001\n\013RequestType\022\r\n\tADD_TOPIC\020\000\022\017\n\013" +
      "ADD_COMMENT\020\001\022\017\n\013DEL_COMMENT\020\002\022\016\n\nUP_COM" +
      "MENT\020\003\022\016\n\nGET_TOPICS\020\004\022\020\n\014GET_COMMENTS\020\005" +
      "\022\032\n\026Add_COMMENT_TO_COMMENT\020\006*\250\001\n\rRequest" +
      "Status\022\r\n\tSTATUS_OK\020\000\022\036\n\032UPDATE_REJECTED" +
      "_NOT_LEADER\020\001\022\023\n\017TEMA_NE_POSTOJI\020\002\022\027\n\023KO" +
      "MENTAR_NE_POSTOJI\020\003\022\036\n\032VREME_ZA_PROMENU_" +
      "JE_PROSLO\020\004\022\032\n\026KOMENTAR_NIJE_IZBRISAN\020\005*" +
      "?\n\tLogStatus\022\n\n\006LOG_OK\020\000\022\014\n\010IO_ERROR\020\001\022\030" +
      "\n\024LOG_HASNT_LAST_ENTRY\020\0022\217\003\n\016AccountServ" +
      "ice\022%\n\014SendNewTopic\022\010.Request\032\t.Response" +
      "\"\000\022.\n\025SendNewCommentToTopic\022\010.Request\032\t." +
      "Response\"\000\022\'\n\016ReplyToComment\022\010.Request\032\t" +
      ".Response\"\000\022(\n\017UpdateMyComment\022\010.Request" +
      "\032\t.Response\"\000\022(\n\017DeleteMyComment\022\010.Reque" +
      "st\032\t.Response\"\000\022%\n\rGetTopicsList\022\010.Reque" +
      "st\032\006.Topic\"\0000\001\022*\n\020GetTopicComments\022\010.Req" +
      "uest\032\010.Comment\"\0000\001\022&\n\tAppendLog\022\t.LogEnt" +
      "ry\032\014.LogResponse\"\000\022.\n\rGetLeaderInfo\022\016.Le" +
      "aderRequest\032\013.LeaderInfo\"\000B\022\n\016gRPCgeneri" +
      "sanoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "RequestId", "Topic", "Comment", "CommentParrent", "OpType", "Zamena", "Topic", "Comment", "CommentParrent", "Zamena", });
    internal_static_Podaci_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Podaci_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Podaci_descriptor,
        new java.lang.String[] { "Comment", "Text", });
    internal_static_SendNewComment_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SendNewComment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendNewComment_descriptor,
        new java.lang.String[] { "Comment", "Topic", });
    internal_static_komentari_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_komentari_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_komentari_descriptor,
        new java.lang.String[] { "ParrentComment", "ChildComment", });
    internal_static_Topic_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Topic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Topic_descriptor,
        new java.lang.String[] { "TopicId", "Text", "User", });
    internal_static_Comment_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Comment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Comment_descriptor,
        new java.lang.String[] { "CommentId", "ParentCommentId", "Text", "TopicId", "User", "Timestamp", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Status", "RequestId", "Message", "Message", });
    internal_static_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogEntry_descriptor,
        new java.lang.String[] { "EntryAtIndex", "LogEntryData", });
    internal_static_LogResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_LogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogResponse_descriptor,
        new java.lang.String[] { "Status", "EntryAtIndex", "LastEntryIndex", "LastEntryIndex", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_LeaderRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_LeaderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderRequest_descriptor,
        new java.lang.String[] { });
    internal_static_LeaderInfo_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_LeaderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderInfo_descriptor,
        new java.lang.String[] { "ImLeader", "HostnamePort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
