// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

public interface komentariOrBuilder extends
    // @@protoc_insertion_point(interface_extends:komentari)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Comment parrentComment = 1;</code>
   * @return Whether the parrentComment field is set.
   */
  boolean hasParrentComment();
  /**
   * <code>.Comment parrentComment = 1;</code>
   * @return The parrentComment.
   */
  gRPCgenerisano.Comment getParrentComment();
  /**
   * <code>.Comment parrentComment = 1;</code>
   */
  gRPCgenerisano.CommentOrBuilder getParrentCommentOrBuilder();

  /**
   * <code>.Comment childComment = 2;</code>
   * @return Whether the childComment field is set.
   */
  boolean hasChildComment();
  /**
   * <code>.Comment childComment = 2;</code>
   * @return The childComment.
   */
  gRPCgenerisano.Comment getChildComment();
  /**
   * <code>.Comment childComment = 2;</code>
   */
  gRPCgenerisano.CommentOrBuilder getChildCommentOrBuilder();
}
