// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

/**
 * Protobuf type {@code komentari}
 */
public final class komentari extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:komentari)
    komentariOrBuilder {
private static final long serialVersionUID = 0L;
  // Use komentari.newBuilder() to construct.
  private komentari(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private komentari() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new komentari();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gRPCgenerisano.F.internal_static_komentari_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gRPCgenerisano.F.internal_static_komentari_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gRPCgenerisano.komentari.class, gRPCgenerisano.komentari.Builder.class);
  }

  public static final int PARRENTCOMMENT_FIELD_NUMBER = 1;
  private gRPCgenerisano.Comment parrentComment_;
  /**
   * <code>.Comment parrentComment = 1;</code>
   * @return Whether the parrentComment field is set.
   */
  @java.lang.Override
  public boolean hasParrentComment() {
    return parrentComment_ != null;
  }
  /**
   * <code>.Comment parrentComment = 1;</code>
   * @return The parrentComment.
   */
  @java.lang.Override
  public gRPCgenerisano.Comment getParrentComment() {
    return parrentComment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : parrentComment_;
  }
  /**
   * <code>.Comment parrentComment = 1;</code>
   */
  @java.lang.Override
  public gRPCgenerisano.CommentOrBuilder getParrentCommentOrBuilder() {
    return parrentComment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : parrentComment_;
  }

  public static final int CHILDCOMMENT_FIELD_NUMBER = 2;
  private gRPCgenerisano.Comment childComment_;
  /**
   * <code>.Comment childComment = 2;</code>
   * @return Whether the childComment field is set.
   */
  @java.lang.Override
  public boolean hasChildComment() {
    return childComment_ != null;
  }
  /**
   * <code>.Comment childComment = 2;</code>
   * @return The childComment.
   */
  @java.lang.Override
  public gRPCgenerisano.Comment getChildComment() {
    return childComment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : childComment_;
  }
  /**
   * <code>.Comment childComment = 2;</code>
   */
  @java.lang.Override
  public gRPCgenerisano.CommentOrBuilder getChildCommentOrBuilder() {
    return childComment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : childComment_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (parrentComment_ != null) {
      output.writeMessage(1, getParrentComment());
    }
    if (childComment_ != null) {
      output.writeMessage(2, getChildComment());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (parrentComment_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getParrentComment());
    }
    if (childComment_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getChildComment());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gRPCgenerisano.komentari)) {
      return super.equals(obj);
    }
    gRPCgenerisano.komentari other = (gRPCgenerisano.komentari) obj;

    if (hasParrentComment() != other.hasParrentComment()) return false;
    if (hasParrentComment()) {
      if (!getParrentComment()
          .equals(other.getParrentComment())) return false;
    }
    if (hasChildComment() != other.hasChildComment()) return false;
    if (hasChildComment()) {
      if (!getChildComment()
          .equals(other.getChildComment())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasParrentComment()) {
      hash = (37 * hash) + PARRENTCOMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getParrentComment().hashCode();
    }
    if (hasChildComment()) {
      hash = (37 * hash) + CHILDCOMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getChildComment().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gRPCgenerisano.komentari parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPCgenerisano.komentari parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPCgenerisano.komentari parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPCgenerisano.komentari parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPCgenerisano.komentari parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPCgenerisano.komentari parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPCgenerisano.komentari parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gRPCgenerisano.komentari parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gRPCgenerisano.komentari parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gRPCgenerisano.komentari parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gRPCgenerisano.komentari parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gRPCgenerisano.komentari parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gRPCgenerisano.komentari prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code komentari}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:komentari)
      gRPCgenerisano.komentariOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gRPCgenerisano.F.internal_static_komentari_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gRPCgenerisano.F.internal_static_komentari_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gRPCgenerisano.komentari.class, gRPCgenerisano.komentari.Builder.class);
    }

    // Construct using gRPCgenerisano.komentari.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      parrentComment_ = null;
      if (parrentCommentBuilder_ != null) {
        parrentCommentBuilder_.dispose();
        parrentCommentBuilder_ = null;
      }
      childComment_ = null;
      if (childCommentBuilder_ != null) {
        childCommentBuilder_.dispose();
        childCommentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gRPCgenerisano.F.internal_static_komentari_descriptor;
    }

    @java.lang.Override
    public gRPCgenerisano.komentari getDefaultInstanceForType() {
      return gRPCgenerisano.komentari.getDefaultInstance();
    }

    @java.lang.Override
    public gRPCgenerisano.komentari build() {
      gRPCgenerisano.komentari result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gRPCgenerisano.komentari buildPartial() {
      gRPCgenerisano.komentari result = new gRPCgenerisano.komentari(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(gRPCgenerisano.komentari result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.parrentComment_ = parrentCommentBuilder_ == null
            ? parrentComment_
            : parrentCommentBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.childComment_ = childCommentBuilder_ == null
            ? childComment_
            : childCommentBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gRPCgenerisano.komentari) {
        return mergeFrom((gRPCgenerisano.komentari)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gRPCgenerisano.komentari other) {
      if (other == gRPCgenerisano.komentari.getDefaultInstance()) return this;
      if (other.hasParrentComment()) {
        mergeParrentComment(other.getParrentComment());
      }
      if (other.hasChildComment()) {
        mergeChildComment(other.getChildComment());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getParrentCommentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getChildCommentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private gRPCgenerisano.Comment parrentComment_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder> parrentCommentBuilder_;
    /**
     * <code>.Comment parrentComment = 1;</code>
     * @return Whether the parrentComment field is set.
     */
    public boolean hasParrentComment() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Comment parrentComment = 1;</code>
     * @return The parrentComment.
     */
    public gRPCgenerisano.Comment getParrentComment() {
      if (parrentCommentBuilder_ == null) {
        return parrentComment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : parrentComment_;
      } else {
        return parrentCommentBuilder_.getMessage();
      }
    }
    /**
     * <code>.Comment parrentComment = 1;</code>
     */
    public Builder setParrentComment(gRPCgenerisano.Comment value) {
      if (parrentCommentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        parrentComment_ = value;
      } else {
        parrentCommentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment parrentComment = 1;</code>
     */
    public Builder setParrentComment(
        gRPCgenerisano.Comment.Builder builderForValue) {
      if (parrentCommentBuilder_ == null) {
        parrentComment_ = builderForValue.build();
      } else {
        parrentCommentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment parrentComment = 1;</code>
     */
    public Builder mergeParrentComment(gRPCgenerisano.Comment value) {
      if (parrentCommentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          parrentComment_ != null &&
          parrentComment_ != gRPCgenerisano.Comment.getDefaultInstance()) {
          getParrentCommentBuilder().mergeFrom(value);
        } else {
          parrentComment_ = value;
        }
      } else {
        parrentCommentBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment parrentComment = 1;</code>
     */
    public Builder clearParrentComment() {
      bitField0_ = (bitField0_ & ~0x00000001);
      parrentComment_ = null;
      if (parrentCommentBuilder_ != null) {
        parrentCommentBuilder_.dispose();
        parrentCommentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Comment parrentComment = 1;</code>
     */
    public gRPCgenerisano.Comment.Builder getParrentCommentBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getParrentCommentFieldBuilder().getBuilder();
    }
    /**
     * <code>.Comment parrentComment = 1;</code>
     */
    public gRPCgenerisano.CommentOrBuilder getParrentCommentOrBuilder() {
      if (parrentCommentBuilder_ != null) {
        return parrentCommentBuilder_.getMessageOrBuilder();
      } else {
        return parrentComment_ == null ?
            gRPCgenerisano.Comment.getDefaultInstance() : parrentComment_;
      }
    }
    /**
     * <code>.Comment parrentComment = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder> 
        getParrentCommentFieldBuilder() {
      if (parrentCommentBuilder_ == null) {
        parrentCommentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder>(
                getParrentComment(),
                getParentForChildren(),
                isClean());
        parrentComment_ = null;
      }
      return parrentCommentBuilder_;
    }

    private gRPCgenerisano.Comment childComment_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder> childCommentBuilder_;
    /**
     * <code>.Comment childComment = 2;</code>
     * @return Whether the childComment field is set.
     */
    public boolean hasChildComment() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.Comment childComment = 2;</code>
     * @return The childComment.
     */
    public gRPCgenerisano.Comment getChildComment() {
      if (childCommentBuilder_ == null) {
        return childComment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : childComment_;
      } else {
        return childCommentBuilder_.getMessage();
      }
    }
    /**
     * <code>.Comment childComment = 2;</code>
     */
    public Builder setChildComment(gRPCgenerisano.Comment value) {
      if (childCommentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        childComment_ = value;
      } else {
        childCommentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment childComment = 2;</code>
     */
    public Builder setChildComment(
        gRPCgenerisano.Comment.Builder builderForValue) {
      if (childCommentBuilder_ == null) {
        childComment_ = builderForValue.build();
      } else {
        childCommentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment childComment = 2;</code>
     */
    public Builder mergeChildComment(gRPCgenerisano.Comment value) {
      if (childCommentBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          childComment_ != null &&
          childComment_ != gRPCgenerisano.Comment.getDefaultInstance()) {
          getChildCommentBuilder().mergeFrom(value);
        } else {
          childComment_ = value;
        }
      } else {
        childCommentBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment childComment = 2;</code>
     */
    public Builder clearChildComment() {
      bitField0_ = (bitField0_ & ~0x00000002);
      childComment_ = null;
      if (childCommentBuilder_ != null) {
        childCommentBuilder_.dispose();
        childCommentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Comment childComment = 2;</code>
     */
    public gRPCgenerisano.Comment.Builder getChildCommentBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getChildCommentFieldBuilder().getBuilder();
    }
    /**
     * <code>.Comment childComment = 2;</code>
     */
    public gRPCgenerisano.CommentOrBuilder getChildCommentOrBuilder() {
      if (childCommentBuilder_ != null) {
        return childCommentBuilder_.getMessageOrBuilder();
      } else {
        return childComment_ == null ?
            gRPCgenerisano.Comment.getDefaultInstance() : childComment_;
      }
    }
    /**
     * <code>.Comment childComment = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder> 
        getChildCommentFieldBuilder() {
      if (childCommentBuilder_ == null) {
        childCommentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder>(
                getChildComment(),
                getParentForChildren(),
                isClean());
        childComment_ = null;
      }
      return childCommentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:komentari)
  }

  // @@protoc_insertion_point(class_scope:komentari)
  private static final gRPCgenerisano.komentari DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gRPCgenerisano.komentari();
  }

  public static gRPCgenerisano.komentari getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<komentari>
      PARSER = new com.google.protobuf.AbstractParser<komentari>() {
    @java.lang.Override
    public komentari parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<komentari> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<komentari> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gRPCgenerisano.komentari getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

