// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

public interface LeaderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LeaderRequest)
    com.google.protobuf.MessageOrBuilder {
}
