// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

public interface PodaciOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Podaci)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Comment comment = 1;</code>
   * @return Whether the comment field is set.
   */
  boolean hasComment();
  /**
   * <code>.Comment comment = 1;</code>
   * @return The comment.
   */
  gRPCgenerisano.Comment getComment();
  /**
   * <code>.Comment comment = 1;</code>
   */
  gRPCgenerisano.CommentOrBuilder getCommentOrBuilder();

  /**
   * <code>string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
