// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 request_id = 1;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>optional .Topic topic = 2;</code>
   * @return Whether the topic field is set.
   */
  boolean hasTopic();
  /**
   * <code>optional .Topic topic = 2;</code>
   * @return The topic.
   */
  gRPCgenerisano.Topic getTopic();
  /**
   * <code>optional .Topic topic = 2;</code>
   */
  gRPCgenerisano.TopicOrBuilder getTopicOrBuilder();

  /**
   * <code>optional .Comment comment = 3;</code>
   * @return Whether the comment field is set.
   */
  boolean hasComment();
  /**
   * <code>optional .Comment comment = 3;</code>
   * @return The comment.
   */
  gRPCgenerisano.Comment getComment();
  /**
   * <code>optional .Comment comment = 3;</code>
   */
  gRPCgenerisano.CommentOrBuilder getCommentOrBuilder();

  /**
   * <code>optional .Comment commentParrent = 4;</code>
   * @return Whether the commentParrent field is set.
   */
  boolean hasCommentParrent();
  /**
   * <code>optional .Comment commentParrent = 4;</code>
   * @return The commentParrent.
   */
  gRPCgenerisano.Comment getCommentParrent();
  /**
   * <code>optional .Comment commentParrent = 4;</code>
   */
  gRPCgenerisano.CommentOrBuilder getCommentParrentOrBuilder();

  /**
   * <code>.RequestType op_type = 5;</code>
   * @return The enum numeric value on the wire for opType.
   */
  int getOpTypeValue();
  /**
   * <code>.RequestType op_type = 5;</code>
   * @return The opType.
   */
  gRPCgenerisano.RequestType getOpType();

  /**
   * <code>optional string zamena = 6;</code>
   * @return Whether the zamena field is set.
   */
  boolean hasZamena();
  /**
   * <code>optional string zamena = 6;</code>
   * @return The zamena.
   */
  java.lang.String getZamena();
  /**
   * <code>optional string zamena = 6;</code>
   * @return The bytes for zamena.
   */
  com.google.protobuf.ByteString
      getZamenaBytes();
}
