// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The status.
   */
  gRPCgenerisano.RequestStatus getStatus();

  /**
   * <code>int32 request_id = 2;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>optional string message = 3;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
