// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

public interface SendNewCommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendNewComment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Comment comment = 1;</code>
   * @return Whether the comment field is set.
   */
  boolean hasComment();
  /**
   * <code>.Comment comment = 1;</code>
   * @return The comment.
   */
  gRPCgenerisano.Comment getComment();
  /**
   * <code>.Comment comment = 1;</code>
   */
  gRPCgenerisano.CommentOrBuilder getCommentOrBuilder();

  /**
   * <code>.Topic topic = 2;</code>
   * @return Whether the topic field is set.
   */
  boolean hasTopic();
  /**
   * <code>.Topic topic = 2;</code>
   * @return The topic.
   */
  gRPCgenerisano.Topic getTopic();
  /**
   * <code>.Topic topic = 2;</code>
   */
  gRPCgenerisano.TopicOrBuilder getTopicOrBuilder();
}
