// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

/**
 * Protobuf type {@code SendNewComment}
 */
public final class SendNewComment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SendNewComment)
    SendNewCommentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendNewComment.newBuilder() to construct.
  private SendNewComment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendNewComment() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SendNewComment();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gRPCgenerisano.F.internal_static_SendNewComment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gRPCgenerisano.F.internal_static_SendNewComment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gRPCgenerisano.SendNewComment.class, gRPCgenerisano.SendNewComment.Builder.class);
  }

  public static final int COMMENT_FIELD_NUMBER = 1;
  private gRPCgenerisano.Comment comment_;
  /**
   * <code>.Comment comment = 1;</code>
   * @return Whether the comment field is set.
   */
  @java.lang.Override
  public boolean hasComment() {
    return comment_ != null;
  }
  /**
   * <code>.Comment comment = 1;</code>
   * @return The comment.
   */
  @java.lang.Override
  public gRPCgenerisano.Comment getComment() {
    return comment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : comment_;
  }
  /**
   * <code>.Comment comment = 1;</code>
   */
  @java.lang.Override
  public gRPCgenerisano.CommentOrBuilder getCommentOrBuilder() {
    return comment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : comment_;
  }

  public static final int TOPIC_FIELD_NUMBER = 2;
  private gRPCgenerisano.Topic topic_;
  /**
   * <code>.Topic topic = 2;</code>
   * @return Whether the topic field is set.
   */
  @java.lang.Override
  public boolean hasTopic() {
    return topic_ != null;
  }
  /**
   * <code>.Topic topic = 2;</code>
   * @return The topic.
   */
  @java.lang.Override
  public gRPCgenerisano.Topic getTopic() {
    return topic_ == null ? gRPCgenerisano.Topic.getDefaultInstance() : topic_;
  }
  /**
   * <code>.Topic topic = 2;</code>
   */
  @java.lang.Override
  public gRPCgenerisano.TopicOrBuilder getTopicOrBuilder() {
    return topic_ == null ? gRPCgenerisano.Topic.getDefaultInstance() : topic_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (comment_ != null) {
      output.writeMessage(1, getComment());
    }
    if (topic_ != null) {
      output.writeMessage(2, getTopic());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (comment_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getComment());
    }
    if (topic_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTopic());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gRPCgenerisano.SendNewComment)) {
      return super.equals(obj);
    }
    gRPCgenerisano.SendNewComment other = (gRPCgenerisano.SendNewComment) obj;

    if (hasComment() != other.hasComment()) return false;
    if (hasComment()) {
      if (!getComment()
          .equals(other.getComment())) return false;
    }
    if (hasTopic() != other.hasTopic()) return false;
    if (hasTopic()) {
      if (!getTopic()
          .equals(other.getTopic())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasComment()) {
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getComment().hashCode();
    }
    if (hasTopic()) {
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gRPCgenerisano.SendNewComment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gRPCgenerisano.SendNewComment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gRPCgenerisano.SendNewComment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gRPCgenerisano.SendNewComment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gRPCgenerisano.SendNewComment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SendNewComment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SendNewComment)
      gRPCgenerisano.SendNewCommentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gRPCgenerisano.F.internal_static_SendNewComment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gRPCgenerisano.F.internal_static_SendNewComment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gRPCgenerisano.SendNewComment.class, gRPCgenerisano.SendNewComment.Builder.class);
    }

    // Construct using gRPCgenerisano.SendNewComment.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      comment_ = null;
      if (commentBuilder_ != null) {
        commentBuilder_.dispose();
        commentBuilder_ = null;
      }
      topic_ = null;
      if (topicBuilder_ != null) {
        topicBuilder_.dispose();
        topicBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gRPCgenerisano.F.internal_static_SendNewComment_descriptor;
    }

    @java.lang.Override
    public gRPCgenerisano.SendNewComment getDefaultInstanceForType() {
      return gRPCgenerisano.SendNewComment.getDefaultInstance();
    }

    @java.lang.Override
    public gRPCgenerisano.SendNewComment build() {
      gRPCgenerisano.SendNewComment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gRPCgenerisano.SendNewComment buildPartial() {
      gRPCgenerisano.SendNewComment result = new gRPCgenerisano.SendNewComment(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(gRPCgenerisano.SendNewComment result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.comment_ = commentBuilder_ == null
            ? comment_
            : commentBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.topic_ = topicBuilder_ == null
            ? topic_
            : topicBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gRPCgenerisano.SendNewComment) {
        return mergeFrom((gRPCgenerisano.SendNewComment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gRPCgenerisano.SendNewComment other) {
      if (other == gRPCgenerisano.SendNewComment.getDefaultInstance()) return this;
      if (other.hasComment()) {
        mergeComment(other.getComment());
      }
      if (other.hasTopic()) {
        mergeTopic(other.getTopic());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCommentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTopicFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private gRPCgenerisano.Comment comment_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder> commentBuilder_;
    /**
     * <code>.Comment comment = 1;</code>
     * @return Whether the comment field is set.
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Comment comment = 1;</code>
     * @return The comment.
     */
    public gRPCgenerisano.Comment getComment() {
      if (commentBuilder_ == null) {
        return comment_ == null ? gRPCgenerisano.Comment.getDefaultInstance() : comment_;
      } else {
        return commentBuilder_.getMessage();
      }
    }
    /**
     * <code>.Comment comment = 1;</code>
     */
    public Builder setComment(gRPCgenerisano.Comment value) {
      if (commentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        comment_ = value;
      } else {
        commentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment comment = 1;</code>
     */
    public Builder setComment(
        gRPCgenerisano.Comment.Builder builderForValue) {
      if (commentBuilder_ == null) {
        comment_ = builderForValue.build();
      } else {
        commentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment comment = 1;</code>
     */
    public Builder mergeComment(gRPCgenerisano.Comment value) {
      if (commentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          comment_ != null &&
          comment_ != gRPCgenerisano.Comment.getDefaultInstance()) {
          getCommentBuilder().mergeFrom(value);
        } else {
          comment_ = value;
        }
      } else {
        commentBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Comment comment = 1;</code>
     */
    public Builder clearComment() {
      bitField0_ = (bitField0_ & ~0x00000001);
      comment_ = null;
      if (commentBuilder_ != null) {
        commentBuilder_.dispose();
        commentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Comment comment = 1;</code>
     */
    public gRPCgenerisano.Comment.Builder getCommentBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCommentFieldBuilder().getBuilder();
    }
    /**
     * <code>.Comment comment = 1;</code>
     */
    public gRPCgenerisano.CommentOrBuilder getCommentOrBuilder() {
      if (commentBuilder_ != null) {
        return commentBuilder_.getMessageOrBuilder();
      } else {
        return comment_ == null ?
            gRPCgenerisano.Comment.getDefaultInstance() : comment_;
      }
    }
    /**
     * <code>.Comment comment = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder> 
        getCommentFieldBuilder() {
      if (commentBuilder_ == null) {
        commentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gRPCgenerisano.Comment, gRPCgenerisano.Comment.Builder, gRPCgenerisano.CommentOrBuilder>(
                getComment(),
                getParentForChildren(),
                isClean());
        comment_ = null;
      }
      return commentBuilder_;
    }

    private gRPCgenerisano.Topic topic_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gRPCgenerisano.Topic, gRPCgenerisano.Topic.Builder, gRPCgenerisano.TopicOrBuilder> topicBuilder_;
    /**
     * <code>.Topic topic = 2;</code>
     * @return Whether the topic field is set.
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.Topic topic = 2;</code>
     * @return The topic.
     */
    public gRPCgenerisano.Topic getTopic() {
      if (topicBuilder_ == null) {
        return topic_ == null ? gRPCgenerisano.Topic.getDefaultInstance() : topic_;
      } else {
        return topicBuilder_.getMessage();
      }
    }
    /**
     * <code>.Topic topic = 2;</code>
     */
    public Builder setTopic(gRPCgenerisano.Topic value) {
      if (topicBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        topic_ = value;
      } else {
        topicBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Topic topic = 2;</code>
     */
    public Builder setTopic(
        gRPCgenerisano.Topic.Builder builderForValue) {
      if (topicBuilder_ == null) {
        topic_ = builderForValue.build();
      } else {
        topicBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Topic topic = 2;</code>
     */
    public Builder mergeTopic(gRPCgenerisano.Topic value) {
      if (topicBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          topic_ != null &&
          topic_ != gRPCgenerisano.Topic.getDefaultInstance()) {
          getTopicBuilder().mergeFrom(value);
        } else {
          topic_ = value;
        }
      } else {
        topicBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Topic topic = 2;</code>
     */
    public Builder clearTopic() {
      bitField0_ = (bitField0_ & ~0x00000002);
      topic_ = null;
      if (topicBuilder_ != null) {
        topicBuilder_.dispose();
        topicBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Topic topic = 2;</code>
     */
    public gRPCgenerisano.Topic.Builder getTopicBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTopicFieldBuilder().getBuilder();
    }
    /**
     * <code>.Topic topic = 2;</code>
     */
    public gRPCgenerisano.TopicOrBuilder getTopicOrBuilder() {
      if (topicBuilder_ != null) {
        return topicBuilder_.getMessageOrBuilder();
      } else {
        return topic_ == null ?
            gRPCgenerisano.Topic.getDefaultInstance() : topic_;
      }
    }
    /**
     * <code>.Topic topic = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gRPCgenerisano.Topic, gRPCgenerisano.Topic.Builder, gRPCgenerisano.TopicOrBuilder> 
        getTopicFieldBuilder() {
      if (topicBuilder_ == null) {
        topicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gRPCgenerisano.Topic, gRPCgenerisano.Topic.Builder, gRPCgenerisano.TopicOrBuilder>(
                getTopic(),
                getParentForChildren(),
                isClean());
        topic_ = null;
      }
      return topicBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SendNewComment)
  }

  // @@protoc_insertion_point(class_scope:SendNewComment)
  private static final gRPCgenerisano.SendNewComment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gRPCgenerisano.SendNewComment();
  }

  public static gRPCgenerisano.SendNewComment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendNewComment>
      PARSER = new com.google.protobuf.AbstractParser<SendNewComment>() {
    @java.lang.Override
    public SendNewComment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SendNewComment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendNewComment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gRPCgenerisano.SendNewComment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

