// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f.proto

package gRPCgenerisano;

public interface TopicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Topic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 topic_id = 1;</code>
   * @return The topicId.
   */
  int getTopicId();

  /**
   * <code>string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string user = 3;</code>
   * @return The user.
   */
  java.lang.String getUser();
  /**
   * <code>string user = 3;</code>
   * @return The bytes for user.
   */
  com.google.protobuf.ByteString
      getUserBytes();
}
